### ISSUE TITLE
Create a management UI for hexathons

### ISSUE THREAD

**Issue by ayush-goyal** [HackGT/api#125]
Create a UI on the admin page to manage hexathons since right now it can only be updated through endpoints. Also, this UI should be able to update the hexathon logo and email header and upload these to the `hexlabs-public-cdn` Google Cloud bucket.

**Comment by Roshan-D** [comment]
You can just create a simple form asking for the below fields. Make sure to only allow people with the exec role to create new hexathons. When adding the emailHeaderImage, upload it to the bucket first and then reference the public URL.

Don't worry about editing the events rn, we just wanna get something out so we can use it for our spring events.

```
{
  name: string;
  shortCode: string;
  isActive: boolean;
  startDate: Date;
  endDate: Date;
  emailHeaderImage?: string;
  coverImage?: string;
}
```

Develop on https://github.com/HackGT/mission-control

**Comment by Roshan-D** [comment]
For the part of the issue where I mentioned uploading an image to the storage bucket, I think it was a little vague so that's my bad. 

If you look [here](https://console.cloud.google.com/storage/browser?project=hexlabs-cloud), we basically have a place to store the email header images and cover images. So, the general flow we want is to be able to upload an image in the create hexathon form, and then when we submit the form to actually upload that image to the google cloud storage bucket. Finally, you can get the public URL of that image and store that in mongo.
